---
output: github_document
---

# niradm-package: Basic analysis of near-infrared data
## Installation and loading
- install the latest version from [GitHub](https://github.com/admedeiros/niradm-package) as follow:
```{r, message=FALSE}
#Install
if(!require(devtools)) install.packages("devtools")
if(!require(niradm)) devtools::install_github("admedeiros/niradm-package")

#Load package
library(niradm)
```

## Examples
### Spectra Visualization
```{r, fig.keep='all', fig.width=10, fig.height=5}
# raw spectra
vizplotraw(nir_seed)
```

```{r  fig.keep='all', fig.width=10, fig.height=5}
# mean spectra per class
vizplotmean(nir_seed)
```

### View of the exploratory principal component analysis
```{r  fig.keep='all', fig.width=20, fig.height=5}
pca(nir_seed,1,2)
```

### Autoscaling and center
```{r, message=FALSE, fig.keep='all', fig.width=20, fig.height=5}
library(ggpubr) #for ggarrange
data(nir_seed)
dados<-scale_center(nir_seed)
a<-vizplotmean(nir_seed)
b<-vizplotmean(dados)
ggarrange(a, b,
  labels = c("A", "B"),
  ncol = 2, nrow = 1)
```

### Applying derivatives with Savitzky-Golay smoothing
```{r  fig.keep='all', fig.width=10, fig.height=5}
data(nir_seed)
a<-vizplotmean(nir_seed)

#Applying 1st derivative with Savitzky-Golay smoothing.
dados<-der_SG(nir_seed,1,2,11)
b<-vizplotmean(dados)

#Applying 2nd derivative with Savitzky-Golay smoothing.
dados<-der_SG(nir_seed,2,2,11)
c<-vizplotmean(dados)
ggarrange(a, b, c, 
labels = c("A", "B", "C"),
ncol = 2, nrow = 2,  widths = 15,
  heights = 10)
```

